// <auto-generated />
using System;
using GuestImporterApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GuestImporterApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419123534_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GuestImporterApi.Data.Guest", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IDIssuePlace")
                        .HasColumnType("text");

                    b.Property<string>("IDNumber")
                        .HasColumnType("text");

                    b.Property<string>("Name_ar")
                        .HasColumnType("text");

                    b.Property<string>("PassportNumber")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("guestName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Guest", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
